const words = [
    { day: '2024-08-01', words: ["The local pub quiz night proved to be an excellent way to immerse myself in British culture"] },
    { day: '2024-08-02', words: ["I discovered a charming flat in the city centre, complete with period features"] },
    { day: '2024-08-03', words: ["Navigating the Tube system became second nature after a few practice runs"] },
    { day: '2024-08-04', words: ["My first Sunday roast experience was a delightful introduction to British cuisine"] },
    { day: '2024-08-05', words: ["Incorporating British idioms into conversations with colleagues has improved my cultural integration"] },
    { day: '2024-08-06', words: ["The weather forecast predicting a fortnight of sunshine seemed almost too good to be true"] },
    { day: '2024-08-07', words: ["Joining a local cricket club offered insights into this quintessentially British sport"] },
    { day: '2024-08-08', words: ["My neighbour's invitation for a cuppa and a chat was a warm welcome to the community"] },
    { day: '2024-08-09', words: ["British workplace etiquette differs subtly from what I'm accustomed to, but I'm adapting quickly"] },
    { day: '2024-08-10', words: ["The multicultural festival in our community showcased the diversity of modern Britain"] },
    { day: '2024-08-11', words: ["Volunteering at a charity shop provided valuable insights into British social norms"] },
    { day: '2024-08-12', words: ["My manager's feedback on my presentation skills was both constructive and encouraging"] },
    { day: '2024-08-13', words: ["The debate club meeting challenged my public speaking abilities in a supportive environment"] },
    { day: '2024-08-14', words: ["A BBC documentary on British political history filled some gaps in my understanding"] },
    { day: '2024-08-15', words: ["The lecture on British literature at the local university was both informative and inspiring"] },
    { day: '2024-08-16', words: ["A lively discussion about current affairs with colleagues over lunch broadened my perspective"] },
    { day: '2024-08-17', words: ["Exploring the farmers' market introduced me to a variety of local produce and cuisines"] },
    { day: '2024-08-18', words: ["The guided tour of Parliament provided fascinating insights into British governance"] },
    { day: '2024-08-19', words: ["A team-building exercise at work improved my collaboration skills and rapport with colleagues"] },
    { day: '2024-08-20', words: ["My language exchange partner helped demystify some perplexing British colloquialisms"] },
    { day: '2024-08-21', words: ["The workshop on British business etiquette highlighted some crucial cultural differences"] },
    { day: '2024-08-22', words: ["A local theatre production exposed me to a range of regional British accents"] },
    { day: '2024-08-23', words: ["The book club's focus on contemporary British authors expanded my literary horizons"] },
    { day: '2024-08-24', words: ["Visiting the local museum enhanced my understanding of the area's rich history"] },
    { day: '2024-08-25', words: ["The community gardening project taught me about native plants and local ecosystems"] },
    { day: '2024-08-26', words: ["The bank holiday weekend provided an opportunity to explore charming nearby towns"] },
    { day: '2024-08-27', words: ["A seminar on British tax and legal systems clarified some complex aspects of life here"] },
    { day: '2024-08-28', words: ["Experiencing the tradition of afternoon tea was a delightful cultural initiation"] },
    { day: '2024-08-29', words: ["Acting as a conversation partner for international students was mutually beneficial"] },
    { day: '2024-08-30', words: ["The local art gallery's exhibition offered insights into contemporary British culture"] },
    { day: '2024-08-31', words: ["Cultural sensitivity training at work highlighted the importance of inclusive practices"] },
    { day: '2024-09-01', words: ["My neighbour's explanation of the NHS system was incredibly helpful"] },
    { day: '2024-09-02', words: ["The local council meeting provided valuable insights into community governance"] },
    { day: '2024-09-03', words: ["A networking event allowed me to practice my small talk skills in a British context"] },
    { day: '2024-09-04', words: ["Joining a local hiking group introduced me to the beauty of the British countryside"] },
    { day: '2024-09-05', words: ["My mentor's feedback on my communication style was invaluable for professional growth"] },
    { day: '2024-09-06', words: ["The workshop on British humour and sarcasm was both enlightening and entertaining"] },
    { day: '2024-09-07', words: ["A local food festival introduced me to various regional cuisines and dialects"] },
    { day: '2024-09-08', words: ["The mock interview session improved my understanding of British professional norms"] },
    { day: '2024-09-09', words: ["A heated debate with colleagues about current political developments was intellectually stimulating"] },
    { day: '2024-09-10', words: ["The lecture on British media's influence on public opinion was thought-provoking"] },
    { day: '2024-09-11', words: ["Learning British Sign Language at the community centre broadened my communication skills"] },
    { day: '2024-09-12', words: ["The roundtable discussion on multicultural integration in the UK was eye-opening"] },
    { day: '2024-09-13', words: ["Observing proceedings at the Crown Court deepened my understanding of the British legal system"] },
    { day: '2024-09-14', words: ["The workshop on writing effective emails in a British business context was practical and useful"] },
    { day: '2024-09-15', words: ["The local history society's talk on the industrial revolution was quite enlightening"] },
    { day: '2024-09-16', words: ["Engaging in a debate on Brexit's impact on local businesses broadened my economic perspective"] },
    { day: '2024-09-17', words: ["Participating in the office bake-off introduced me to traditional British desserts"] },
    { day: '2024-09-18', words: ["The seminar on British workplace rights and employment law was incredibly informative"] },
    { day: '2024-09-19', words: ["A local amateur dramatics performance showcased a variety of regional accents and dialects"] },
    { day: '2024-09-20', words: ["The cultural exchange program at my company's international office was enlightening"] },
    { day: '2024-09-21', words: ["Exploring the local archives provided fascinating insights into the area's rich history"] },
    { day: '2024-09-22', words: ["Learning about British understatement in communication has improved my interpersonal skills"] },
    { day: '2024-09-23', words: ["The company's AGM exposed me to formal British business language and practices"] },
    { day: '2024-09-24', words: ["Joining a local choir has improved my pronunciation and taught me traditional songs"] },
    { day: '2024-09-25', words: ["The mock parliamentary debate enhanced my understanding of British political processes"] },
    { day: '2024-09-26', words: ["The lecture on the evolution of English in Britain was linguistically fascinating"] },
    { day: '2024-09-27', words: ["The local science festival introduced cutting-edge research and expanded my technical vocabulary"] },
    { day: '2024-09-28', words: ["Learning about British etiquette and social norms has smoothed my social interactions"] },
    { day: '2024-09-29', words: ["A lively debate about NHS reforms with colleagues broadened my understanding of healthcare issues"] },
    { day: '2024-09-30', words: ["The seminar on British constitutional monarchy clarified this unique political system"] },
    { day: '2024-10-01', words: ["The faculty mixer provided an excellent opportunity to network with fellow academics"] },
    { day: '2024-10-02', words: ["Discussing sustainable urban development in British cities was intellectually stimulating"] },
    { day: '2024-10-03', words: ["Our department's brainstorming session generated innovative ideas for our research project"] },
    { day: '2024-10-04', words: ["Learning about UK academic funding systems was crucial for my research plans"] },
    { day: '2024-10-05', words: ["Presenting my research at the university's cultural exchange fair was a rewarding experience"] },
    { day: '2024-10-06', words: ["The local debating society has significantly improved my public speaking skills"] },
    { day: '2024-10-07', words: ["Co-authoring a paper on emerging trends in our field has been an enriching experience"] },
    { day: '2024-10-08', words: ["The lecture on Brexit's impact on academic collaborations was highly relevant to my work"] },
    { day: '2024-10-09', words: ["Exploring effective teaching methods in higher education has enhanced my pedagogical skills"] },
    { day: '2024-10-10', words: ["Learning about academic publishing in British and international journals was invaluable"] },
    { day: '2024-10-11', words: ["Our research group's meeting to prepare for the upcoming conference was highly productive"] },
    { day: '2024-10-12', words: ["The guest lecture by a renowned expert in my field was truly inspiring"] },
    { day: '2024-10-13', words: ["Presenting my findings at the interdisciplinary research symposium was a highlight"] },
    { day: '2024-10-14', words: ["The panel discussion on the future of British higher education was thought-provoking"] },
    { day: '2024-10-15', words: ["Our department's peer review session provided valuable feedback on our research projects"] },
    { day: '2024-10-16', words: ["Mastering advanced statistical software has significantly enhanced my research capabilities"] },
    { day: '2024-10-17', words: ["The faculty meeting on implementing new teaching technologies was forward-thinking"] },
    { day: '2024-10-18', words: ["Collaborating with colleagues from other UK universities has broadened my research perspective"] },
    { day: '2024-10-19', words: ["Presenting our research findings at the departmental colloquium was well-received"] },
    { day: '2024-10-20', words: ["The seminar on ethical considerations in UK academic research was crucial"] },
    { day: '2024-10-21', words: ["Learning advanced research techniques has significantly improved my academic output"] },
    { day: '2024-10-22', words: ["The faculty development program on innovative teaching methods was enlightening"] },
    { day: '2024-10-23', words: ["The visiting scholar's lecture on recent developments in our field was insightful"] },
    { day: '2024-10-24', words: ["Presenting my research paper at the sustainable development conference was rewarding"] },
    { day: '2024-10-25', words: ["The networking event with industry professionals opened up new collaborative opportunities"] },
    { day: '2024-10-26', words: ["Learning effective grant proposal writing for UK research councils was invaluable"] },
    { day: '2024-10-27', words: ["Our research group's brainstorming session generated exciting new project ideas"] },
    { day: '2024-10-28', words: ["The seminar on AI's impact on academic disciplines was thought-provoking"] },
    { day: '2024-10-29', words: ["The panel discussion on the future of work in the digital age was highly relevant"] },
    { day: '2024-10-30', words: ["Engaging in a cross-disciplinary research initiative has broadened my academic perspective"] },
    { day: '2024-10-31', words: ["The Halloween-themed social event at the university was a fun cultural experience"] },
    { day: '2024-11-01', words: ["Presenting at the department's monthly seminar series was a valuable experience"] },
    { day: '2024-11-02', words: ["The public lecture on climate change provided crucial insights into a global issue"] },
    { day: '2024-11-03', words: ["Improving my academic writing and publishing strategies has been beneficial"] },
    { day: '2024-11-04', words: ["Our research team's progress meeting helped clarify our project's next steps"] },
    { day: '2024-11-05', words: ["Discussing universities' role in promoting social justice was thought-provoking"] },
    { day: '2024-11-06', words: ["The seminar on research ethics reinforced the importance of integrity in academic work"] },
    { day: '2024-11-07', words: ["Learning about the latest advancements in my field has been intellectually stimulating"] },
    { day: '2024-11-08', words: ["Brainstorming ideas for an interdisciplinary research project was exciting"] },
    { day: '2024-11-09', words: ["Exploring effective teaching methods for international students has improved my pedagogy"] },
    { day: '2024-11-10', words: ["The symposium on emerging technologies' societal impact was eye-opening"] },
    { day: '2024-11-11', words: ["The Remembrance Day ceremony at the university was a moving cultural experience"] },
    { day: '2024-11-12', words: ["The visiting professor's lecture on global education trends was thought-provoking"] },
    { day: '2024-11-13', words: ["Contributing to curriculum updates has been a rewarding professional experience"] },
    { day: '2024-11-14', words: ["Learning about securing international research collaborations was valuable"] },
    { day: '2024-11-15', words: ["The seminar on Brexit's impact on higher education funding was highly relevant"] },
    { day: '2024-11-16', words: ["Presenting our research findings at the national conference in London was a highlight"] },
    { day: '2024-11-17', words: ["Mastering digital tools for academic research has enhanced my productivity"] },
    { day: '2024-11-18', words: ["The panel on diversity and inclusion in academia was enlightening"] },
    { day: '2024-11-19', words: ["Exploring the future of AI across various industries was fascinating"] },
    { day: '2024-11-20', words: ["Planning our upcoming research project has been an exciting process"] },
    { day: '2024-11-21', words: ["The webinar on effective online teaching strategies was incredibly useful"] },
    { day: '2024-11-22', words: ["Learning about grant writing and funding applications has been crucial"] },
    { day: '2024-11-23', words: ["The lecture on British literature's evolution deepened my cultural understanding"] },
    { day: '2024-11-24', words: ["Discussing climate change's impact on urban planning was thought-provoking"] },
    { day: '2024-11-25', words: ["Exploring innovative research methods has opened up new possibilities in my work"] },
    { day: '2024-11-26', words: ["The symposium on renewable energy technologies was inspiring"] },
    { day: '2024-11-27', words: ["Learning to apply big data in social sciences research has been transformative"] },
    { day: '2024-11-28', words: ["Developing our collaborative research proposal was a rewarding process"] },
    { day: '2024-11-29', words: ["The discussion on technology's role in education reform was enlightening"] },
    { day: '2024-11-30', words: ["Exploring the interplay between politics and economics broadened my perspective"] },
    { day: '2024-12-01', words: ["Understanding the impact of globalization on higher education has been eye-opening"] },
    { day: '2024-12-02', words: ["Presenting our research at the international conference in Edinburgh was a highlight"] },
    { day: '2024-12-03', words: ["Exploring the use of machine learning in academic research has been transformative"] },
    { day: '2024-12-04', words: ["The panel discussion on the future of work in the digital era was highly relevant"] },
    { day: '2024-12-05', words: ["Learning about AI's impact on various academic disciplines was enlightening"] },
    { day: '2024-12-06', words: ["Planning our next research project has been an exciting and collaborative process"] },
    { day: '2024-12-07', words: ["Exploring effective teaching strategies for diverse student populations was invaluable"] },
    { day: '2024-12-08', words: ["The symposium on digital humanities highlighted the future of this interdisciplinary field"] },
    { day: '2024-12-09', words: ["The lecture on the evolution of British political thought was deeply informative"] },
    { day: '2024-12-10', words: ["Discussing Brexit's impact on higher education provided crucial insights"] },
    { day: '2024-12-11', words: ["Mastering digital tools for academic research has significantly improved my productivity"] }, 
    { day: '2024-12-12', words: ["Blimey, the Christmas lights in the city centre are absolutely stunning!"] },
    { day: '2024-12-13', words: ["Fancy a cuppa? It's the perfect weather for a warm cup of tea."] },
    { day: '2024-12-14', words: ["It's all gone pear-shaped with our holiday travel plans due to the snowstorm."] },
    { day: '2024-12-15', words: ["I had a lovely chinwag with my neighbour about our holiday traditions."] },
    { day: '2024-12-16', words: ["The weather is absolutely minging today, isn't it?"] },
    { day: '2024-12-17', words: ["I quite fancy the idea of a quiet night in with a good book."] },
    { day: '2024-12-18', words: ["The party was chockablock with people, but it was smashing fun."] },
    { day: '2024-12-19', words: ["I'm knackered after all the holiday shopping; I think I'll have an early night."] },
    { day: '2024-12-20', words: ["The decorations in the high street are the bee's knees this year."] },
    { day: '2024-12-21', words: ["Don't get your knickers in a twist; everything will be sorted for the Christmas dinner."] },
    { day: '2024-12-22', words: ["We had a great chinwag about our plans for the New Year."] },
    { day: '2024-12-23', words: ["The Christmas market was absolutely ace; I found some lovely gifts."] },
    { day: '2024-12-24', words: ["It's raining cats and dogs, perfect weather for staying in and watching a film."] },
    { day: '2024-12-25', words: ["Merry Christmas! I hope your day is absolutely smashing."] },
    { day: '2024-12-26', words: ["The Boxing Day sales were a bit of a faff, but I managed to get some good deals."] },
    { day: '2024-12-27', words: ["I was gobsmacked by the turnout at the post-Christmas party."] },
    { day: '2024-12-28', words: ["That new restaurant in town is supposed to be the bee's knees; fancy trying it out?"] },
    { day: '2024-12-29', words: ["I'm feeling a bit peckish; fancy a trip to the chippy?"] },
    { day: '2024-12-30', words: ["The New Year's Eve plans are all sorted; it's going to be a blast."] },
    { day: '2024-12-31', words: ["Happy New Year! Let's make it a jolly good one."] },
    { day: '2025-01-01', words: ["I'm feeling a bit knackered after the New Year's celebrations; need a quiet day."] },
    { day: '2025-01-02', words: ["Let's have a chinwag over a cuppa and catch up on the holidays."] },
    { day: '2025-01-03', words: ["The weather is a bit rubbish today, isn't it?"] },
    { day: '2025-01-04', words: ["I was absolutely gobsmacked by the New Year's fireworks display."] },
    { day: '2025-01-05', words: ["Fancy a cuppa? I could use a good chat."] },
    { day: '2025-01-06', words: ["It's all gone pear-shaped with the travel plans, but we'll sort it out."] },
    { day: '2025-01-07', words: ["I had a lovely chinwag with my colleague about our New Year's resolutions."] },
    { day: '2025-01-08', words: ["The weather is absolutely minging today, isn't it?"] },
    { day: '2025-01-09', words: ["I quite fancy the idea of a weekend getaway to the countryside."] },
    { day: '2025-01-10', words: ["The office was chockablock with people today; everyone is back from the holidays."] },
    { day: '2025-01-11', words: ["I'm knackered after the first week back at work; looking forward to a relaxing weekend."] },
    { day: '2025-01-12', words: ["The new coffee shop in town is the bee's knees; you should check it out."] },
    { day: '2025-01-13', words: ["Don't get your knickers in a twist; we'll figure out the project details."] },
    { day: '2025-01-14', words: ["We had a great chinwag about our plans for the upcoming conference."] },
    { day: '2025-01-15', words: ["The presentation was absolutely ace; well done!"] },
    { day: '2025-01-16', words: ["It's raining cats and dogs, perfect weather for staying in and reading."] },
    { day: '2025-01-17', words: ["The new exhibit at the museum is supposed to be smashing; fancy going this weekend?"] },
    { day: '2025-01-18', words: ["I'm feeling a bit peckish; fancy grabbing a bite to eat?"] },
    { day: '2025-01-19', words: ["The weekend plans are all sorted; it's going to be great."] },
    { day: '2025-01-20', words: ["The meeting went really well; everyone was on the same page."] },
    { day: '2025-01-21', words: ["I'm feeling a bit knackered; need to catch up on some sleep."] },
    { day: '2025-01-22', words: ["Let's have a chinwag over lunch and discuss the project."] },
    { day: '2025-01-23', words: ["The weather is a bit rubbish today, isn't it?"] },
    { day: '2025-01-24', words: ["I was absolutely gobsmacked by the news we received today."] },
    { day: '2025-01-25', words: ["Fancy a cuppa? I could use a break."] },
    { day: '2025-01-26', words: ["It's all gone pear-shaped with the event planning, but we'll sort it out."] },
    { day: '2025-01-27', words: ["I had a lovely chinwag with my friend about our weekend plans."] },
    { day: '2025-01-28', words: ["The weather is absolutely minging today, isn't it?"] },
    { day: '2025-01-29', words: ["I quite fancy the idea of a movie night this weekend."] },
    { day: '2025-01-30', words: ["The office was chockablock with people today; everyone is back from the holidays."] },
    { day: '2025-01-31', words: ["I'm knackered after the busy week; looking forward to a relaxing weekend."] },
    { day: '2025-02-01', words: ["The new restaurant in town is the bee's knees; you should check it out."] },
    { day: '2025-02-02', words: ["Don't get your knickers in a twist; we'll figure out the details."] },
    { day: '2025-02-03', words: ["We had a great chinwag about our plans for the upcoming event."] },
    { day: '2025-02-04', words: ["The presentation was absolutely ace; well done!"] },
    { day: '2025-02-05', words: ["It's raining cats and dogs, perfect weather for staying in and watching a film."] },
    { day: '2025-02-06', words: ["The new exhibit at the gallery is supposed to be smashing; fancy going this weekend?"] },
    { day: '2025-02-07', words: ["I'm feeling a bit peckish; fancy grabbing a bite to eat?"] },
    { day: '2025-02-08', words: ["The weekend plans are all sorted; it's going to be great."] },
    { day: '2025-02-09', words: ["The meeting went really well; everyone was on the same page."] },
    { day: '2025-02-10', words: ["I'm feeling a bit knackered; need to catch up on some sleep."] },
    { day: '2025-02-11', words: ["Let's have a chinwag over lunch and discuss the project."] },
    { day: '2025-02-12', words: ["The weather is a bit rubbish today, isn't it?"] },
    { day: '2025-02-13', words: ["I was absolutely gobsmacked by the news we received today."] },
    { day: '2025-02-14', words: ["Fancy a cuppa? I could use a break."] },
    { day: '2025-02-15', words: ["It's all gone pear-shaped with the event planning, but we'll sort it out."] },
    { day: '2025-02-16', words: ["I had a lovely chinwag with my friend about our weekend plans."] },
    { day: '2025-02-17', words: ["The weather is absolutely minging today, isn't it?"] },
    { day: '2025-02-18', words: ["I quite fancy the idea of a movie night this weekend."] },
    { day: '2025-02-19', words: ["The office was chockablock with people today; everyone is back from the holidays."] },
    { day: '2025-02-20', words: ["I'm knackered after the busy week; looking forward to a relaxing weekend."] },
    { day: '2025-02-21', words: ["The new restaurant in town is the bee's knees; you should check it out."] },
    { day: '2025-02-22', words: ["Don't get your knickers in a twist; we'll figure out the details."] },
    { day: '2025-02-23', words: ["We had a great chinwag about our plans for the upcoming event."] },
    { day: '2025-02-24', words: ["The presentation was absolutely ace; well done!"] },
    { day: '2025-02-25', words: ["It's raining cats and dogs, perfect weather for staying in and watching a film."] },
    { day: '2025-02-26', words: ["The new exhibit at the gallery is supposed to be smashing; fancy going this weekend?"] },
    { day: '2025-02-27', words: ["I'm feeling a bit peckish; fancy grabbing a bite to eat?"] },
    { day: '2025-02-28', words: ["The weekend plans are all sorted; it's going to be great."] },
    { day: '2025-02-29', words: ["The meeting went really well; everyone was on the same page."] },
    { day: '2025-03-01', words: ["I'm feeling a bit knackered; need to catch up on some sleep."] },
    { day: '2025-03-02', words: ["Let's have a chinwag over lunch and discuss the project."] },
    { day: '2025-03-03', words: ["The weather is a bit rubbish today, isn't it?"] },
    { day: '2025-03-04', words: ["I was absolutely gobsmacked by the news we received today."] },
    { day: '2025-03-05', words: ["Fancy a cuppa? I could use a break."] },
    { day: '2025-03-06', words: ["It's all gone pear-shaped with the event planning, but we'll sort it out."] },
    { day: '2025-03-07', words: ["I had a lovely chinwag with my friend about our weekend plans."] },
    { day: '2025-03-08', words: ["The weather is absolutely minging today, isn't it?"] },
    { day: '2025-03-09', words: ["I quite fancy the idea of a movie night this weekend."] },
    { day: '2025-03-10', words: ["The office was chockablock with people today; everyone is back from the holidays."] },
    { day: '2025-03-11', words: ["I'm knackered after the busy week; looking forward to a relaxing weekend."] },
    { day: '2025-03-12', words: ["The new restaurant in town is the bee's knees; you should check it out."] },
    { day: '2025-03-13', words: ["Don't get your knickers in a twist; we'll figure out the details."] },
    { day: '2025-03-14', words: ["We had a great chinwag about our plans for the upcoming event."] },
    { day: '2025-03-15', words: ["The presentation was absolutely ace; well done!"] },
    { day: '2025-03-16', words: ["It's raining cats and dogs, perfect weather for staying in and watching a film."] },
    { day: '2025-03-17', words: ["The new exhibit at the gallery is supposed to be smashing; fancy going this weekend?"] },
    { day: '2025-03-18', words: ["I'm feeling a bit peckish; fancy grabbing a bite to eat?"] },
    { day: '2025-03-19', words: ["The weekend plans are all sorted; it's going to be great."] },
    { day: '2025-03-20', words: ["The meeting went really well; everyone was on the same page."] },
    { day: '2025-03-21', words: ["I'm feeling a bit knackered; need to catch up on some sleep."] },
    { day: '2025-03-22', words: ["Let's have a chinwag over lunch and discuss the project."] },
    { day: '2025-03-23', words: ["The weather is a bit rubbish today, isn't it?"] },
    { day: '2025-03-24', words: ["I was absolutely gobsmacked by the news we received today."] },
    { day: '2025-03-25', words: ["Fancy a cuppa? I could use a break."] },
    { day: '2025-03-26', words: ["It's all gone pear-shaped with the event planning, but we'll sort it out."] },
    { day: '2025-03-27', words: ["I had a lovely chinwag with my friend about our weekend plans."] },
    { day: '2025-03-28', words: ["The weather is absolutely minging today, isn't it?"] },
    { day: '2025-03-29', words: ["I quite fancy the idea of a movie night this weekend."] },
    { day: '2025-03-30', words: ["The office was chockablock with people today; everyone is back from the holidays."] },
    { day: '2025-03-31', words: ["I'm knackered after the busy week; looking forward to a relaxing weekend."] },
    { day: '2025-04-01', words: ["The new restaurant in town is the bee's knees; you should check it out."] }
];

