const words = [
    { day: '2024-09-01', words: ["What", "does", "the", "skeleton", "do"] },
    { day: '2024-09-02', words: ["How", "does", "the", "water", "cycle", "work"] },
    { day: '2024-09-03', words: ["What", "do", "bacteria", "do"] },
    { day: '2024-09-04', words: ["Who", "is", "the", "composer", "of", "this", "piece"] },
    { day: '2024-09-05', words: ["What", "is", "the", "temperature", "today"] },
    { day: '2024-09-06', words: ["How", "does", "democracy", "work"] },
    { day: '2024-09-07', words: ["What", "does", "the", "painter", "use"] },
    { day: '2024-09-08', words: ["How", "does", "photosynthesis", "happen"] },
    { day: '2024-09-09', words: ["What", "does", "the", "seismograph", "measure"] },
    { day: '2024-09-10', words: ["How", "do", "you", "solve", "an", "equation"] },
    { day: '2024-09-11', words: ["What", "is", "a", "niche", "in", "an", "ecosystem"] },
    { day: '2024-09-12', words: ["How", "does", "a", "neuron", "send", "signals"] },
    { day: '2024-09-13', words: ["What", "is", "an", "alloy"] },
    { day: '2024-09-14', words: ["What", "does", "this", "poem", "mean"] },
    { day: '2024-09-15', words: ["How", "does", "the", "congress", "pass", "laws"] },
    { day: '2024-09-16', words: ["What", "is", "a", "galaxy"] },
    { day: '2024-09-17', words: ["Where", "is", "the", "equator", "on", "the", "map"] },
    { day: '2024-09-18', words: ["What", "does", "deciduous", "mean"] },
    { day: '2024-09-19', words: ["How", "do", "you", "spell", "this", "word"] },
    { day: '2024-09-20', words: ["What", "kind", "of", "energy", "is", "wind"] },
    { day: '2024-09-21', words: ["How", "do", "you", "simplify", "this", "expression"] },
    { day: '2024-09-22', words: ["What", "does", "an", "autotroph", "do"] },
    { day: '2024-09-23', words: ["Where", "is", "the", "prime", "meridian", "on", "the", "globe"] },
    { day: '2024-09-24', words: ["What", "is", "a", "quark"] },
    { day: '2024-09-25', words: ["What", "does", "the", "orchestra", "play"] },
    { day: '2024-09-26', words: ["How", "does", "a", "thermometer", "work"] },
    { day: '2024-09-27', words: ["What", "does", "cartilage", "do"] },
    { day: '2024-09-28', words: ["How", "does", "the", "senate", "make", "decisions"] },
    { day: '2024-09-29', words: ["What", "is", "a", "variable", "in", "math"] },
    { day: '2024-09-30', words: ["How", "do", "you", "identify", "a", "broadleaf", "tree"] }
];
