{ day: '2024-07-16', words: ["The", "boy", "jumps", "high", "in", "the", "park"] },
    { day: '2024-07-17', words: ["She", "loves", "to", "play", "with", "her", "doll"] },
    { day: '2024-07-18', words: ["The", "sun", "shines", "bright", "in", "the", "sky"] },
    { day: '2024-07-19', words: ["He", "rides", "his", "bike", "to", "the", "shop"] },
    { day: '2024-07-20', words: ["We", "bake", "cookies", "in", "the", "kitchen"] },
    { day: '2024-07-21', words: ["The", "dog", "runs", "fast", "in", "the", "yard"] },
    { day: '2024-07-22', words: ["She", "paints", "a", "picture", "with", "bright", "colors"] },
    { day: '2024-07-23', words: ["The", "baby", "sleeps", "in", "the", "crib"] },
    { day: '2024-07-24', words: ["He", "builds", "a", "tower", "with", "blocks"] },
    { day: '2024-07-25', words: ["We", "read", "a", "story", "before", "bedtime"] },
    { day: '2024-07-26', words: ["The", "cat", "chases", "a", "mouse", "in", "the", "garden"] },
    { day: '2024-07-27', words: ["She", "jumps", "rope", "with", "her", "friends"] },
    { day: '2024-07-28', words: ["The", "bird", "sings", "a", "song", "in", "the", "tree"] },
    { day: '2024-07-29', words: ["He", "draws", "a", "house", "with", "crayons"] },
    { day: '2024-07-30', words: ["We", "plant", "flowers", "in", "the", "garden"] },
    { day: '2024-07-31', words: ["The", "fish", "swims", "in", "the", "pond"] },
    { day: '2024-08-01', words: ["She", "rides", "her", "scooter", "on", "the", "sidewalk"] },
    { day: '2024-08-02', words: ["The", "car", "drives", "down", "the", "street"] },
    { day: '2024-08-03', words: ["He", "eats", "a", "sandwich", "for", "lunch"] },
    { day: '2024-08-04', words: ["We", "play", "games", "at", "the", "park"] },
    { day: '2024-08-05', words: ["The", "cow", "gives", "milk", "on", "the", "farm"] },
    { day: '2024-08-06', words: ["She", "wears", "a", "hat", "in", "the", "sun"] },
    { day: '2024-08-07', words: ["The", "tree", "has", "green", "leaves"] },
    { day: '2024-08-08', words: ["He", "finds", "a", "shell", "on", "the", "beach"] },
    { day: '2024-08-09', words: ["We", "watch", "a", "movie", "at", "home"] },
    { day: '2024-08-10', words: ["The", "kite", "flies", "high", "in", "the", "sky"] },
    { day: '2024-08-11', words: ["She", "catches", "a", "ball", "at", "the", "park"] },
    { day: '2024-08-12', words: ["The", "boat", "sails", "on", "the", "lake"] },
    { day: '2024-08-13', words: ["He", "climbs", "a", "tree", "in", "the", "yard"] },
    { day: '2024-08-14', words: ["We", "make", "a", "cake", "for", "a", "party"] },
    { day: '2024-08-15', words: ["The", "rabbit", "hops", "in", "the", "field"] },
    { day: '2024-08-16', words: ["She", "draws", "a", "sun", "with", "chalk"] },
    { day: '2024-08-17', words: ["The", "horse", "runs", "fast", "in", "the", "meadow"] },
    { day: '2024-08-18', words: ["He", "reads", "a", "book", "about", "space"] },
    { day: '2024-08-19', words: ["We", "build", "a", "sandcastle", "at", "the", "beach"] },
    { day: '2024-08-20', words: ["The", "duck", "swims", "in", "the", "pond"] },
    { day: '2024-08-21', words: ["She", "writes", "a", "letter", "to", "her", "friend"] },
    { day: '2024-08-22', words: ["The", "frog", "jumps", "into", "the", "water"] },
    { day: '2024-08-23', words: ["He", "paints", "a", "rainbow", "with", "watercolors"] },
    { day: '2024-08-24', words: ["We", "sing", "songs", "in", "the", "classroom"] },
    { day: '2024-08-25', words: ["The", "puppy", "plays", "with", "a", "ball"] },
    { day: '2024-08-26', words: ["She", "bakes", "cookies", "with", "her", "mum"] },
    { day: '2024-08-27', words: ["The", "wind", "blows", "the", "leaves", "around"] },
    { day: '2024-08-28', words: ["He", "rides", "a", "horse", "at", "the", "farm"] },
    { day: '2024-08-29', words: ["We", "have", "a", "picnic", "under", "the", "tree"] },
    { day: '2024-08-30', words: ["The", "butterfly", "flies", "over", "the", "flowers"] },
    { day: '2024-08-31', words: ["The", "train", "goes", "fast", "on", "the", "tracks"] },
    { day: '2024-09-01', words: ["What", "does", "this", "bone", "do"] },
    { day: '2024-09-02', words: ["How", "does", "this", "rain", "form"] },
    { day: '2024-09-03', words: ["What", "is", "this", "germ"] },
    { day: '2024-09-04', words: ["Who", "made", "this", "music"] },
    { day: '2024-09-05', words: ["What", "is", "the", "temperature"] },
    { day: '2024-09-06', words: ["How", "do", "these", "rules", "work"] },
    { day: '2024-09-07', words: ["What", "does", "this", "artist", "paint"] },
    { day: '2024-09-08', words: ["How", "does", "this", "plant", "grow"] },
    { day: '2024-09-09', words: ["What", "does", "this", "tool", "do"] },
    { day: '2024-09-10', words: ["How", "do", "you", "solve", "this", "math", "problem"] },
    { day: '2024-09-11', words: ["What", "is", "this", "animal's", "home"] },
    { day: '2024-09-12', words: ["How", "does", "this", "brain", "work"] },
    { day: '2024-09-13', words: ["What", "is", "this", "metal"] },
    { day: '2024-09-14', words: ["What", "is", "this", "poem", "about"] },
    { day: '2024-09-15', words: ["How", "does", "this", "law", "help"] },
    { day: '2024-09-16', words: ["What", "is", "this", "planet"] },
    { day: '2024-09-17', words: ["Where", "is", "this", "place", "on", "the", "map"] },
    { day: '2024-09-18', words: ["What", "tree", "is", "this"] },
    { day: '2024-09-19', words: ["How", "do", "you", "say", "this", "letter"] },
    { day: '2024-09-20', words: ["What", "kind", "of", "power", "is", "this"] },
    { day: '2024-09-21', words: ["How", "do", "you", "add", "these", "numbers"] },
    { day: '2024-09-22', words: ["What", "does", "this", "plant", "need"] },
    { day: '2024-09-23', words: ["Where", "is", "this", "line", "on", "the", "globe"] },
    { day: '2024-09-24', words: ["What", "is", "this", "tiny", "part"] },
    { day: '2024-09-25', words: ["What", "does", "this", "leader", "do"] },
    { day: '2024-09-26', words: ["How", "does", "this", "thing", "tell", "temperature"] },
    { day: '2024-09-27', words: ["What", "is", "this", "part", "of", "the", "body"] },
    { day: '2024-09-28', words: ["How", "does", "this", "rule", "work"] },
    { day: '2024-09-29', words: ["What", "is", "this", "number"] },
    { day: '2024-09-30', words: ["How", "can", "you", "find", "this", "tree"] } 
];
