const words = [
    { day: '2024-07-16', words: ["the", "that", "not", "look", "put", "could"] },
    { day: '2024-07-17', words: ["and", "with", "then", "don't", "come", "house"] },
    { day: '2024-07-18', words: ["a", "all", "were", "old", "go", "will"] },
    { day: '2024-07-19', words: ["to", "up", "no", "mum", "day", "made"] },
    { day: '2024-07-20', words: ["said", "in", "back", "time", "by", "time"] },
    { day: '2024-07-21', words: ["we", "are", "as", "one", "from", "into"] },
    { day: '2024-07-22', words: ["he", "it", "little", "me", "children", "too"] },
    { day: '2024-07-23', words: ["i", "of", "my", "mr", "if", "help"] },
    { day: '2024-07-24', words: ["her", "you", "had", "mrs", "i'm", "oh"] },
    { day: '2024-07-25', words: ["here", "on", "out", "do", "here", "just"] },
    { day: '2024-07-26', words: ["asked", "they", "this", "get", "your", "their"] },
    { day: '2024-07-27', words: ["there", "when", "is", "down", "off", "an"] },
    { day: '2024-07-28', words: ["she", "have", "dad", "very", "saw", "went"] },
    { day: '2024-07-29', words: ["big", "about", "people", "some", "be", "him"] },
    { day: '2024-07-30', words: ["now", "looked", "make", "but", "for", "them"] },
    { day: '2024-07-31', words: ["oh", "it's", "his", "at", "one", "called"] },
    { day: '2024-08-01', words: ["What", "is", "that", "cat", "doing", "on", "that", "mat"] },
    { day: '2024-08-02', words: ["How", "is", "that", "big", "red", "apple"] },
    { day: '2024-08-03', words: ["Where", "is", "that", "moon", "in", "that", "sky"] },
    { day: '2024-08-04', words: ["What", "time", "is", "it", "to", "sit", "on", "that", "chair"] },
    { day: '2024-08-05', words: ["How", "fast", "is", "that", "car", "going"] },
    { day: '2024-08-06', words: ["What", "do", "you", "use", "to", "write", "with", "this", "pen"] },
    { day: '2024-08-07', words: ["What", "makes", "that", "sun", "so", "bright"] },
    { day: '2024-08-08', words: ["What", "colors", "are", "these", "balls"] },
    { day: '2024-08-09', words: ["Why", "does", "that", "dog", "bark", "loudly"] },
    { day: '2024-08-10', words: ["What", "toy", "car", "is", "that"] },
    { day: '2024-08-11', words: ["Where", "is", "that", "cat", "sleeping", "now"] },
    { day: '2024-08-12', words: ["What", "do", "you", "see", "outside", "that", "green", "tree"] },
    { day: '2024-08-13', words: ["How", "often", "do", "you", "drink", "this", "milk", "every", "day"] },
    { day: '2024-08-14', words: ["When", "do", "we", "go", "to", "that", "park", "to", "play"] },
    { day: '2024-08-15', words: ["Who", "cooks", "that", "dinner", "for", "us"] },
    { day: '2024-08-16', words: ["What", "does", "she", "read", "before", "that", "bed"] },
    { day: '2024-08-17', words: ["How", "do", "we", "play", "with", "these", "blocks", "and", "toys"] },
    { day: '2024-08-18', words: ["What", "do", "you", "love", "to", "eat", "these"] },
    { day: '2024-08-19', words: ["Who", "likes", "to", "play", "outside", "with", "these", "friends"] },
    { day: '2024-08-20', words: ["Where", "does", "that", "bird", "fly", "in", "the", "sky"] }
];
