const words = [
    { day: '2024-12-01', words: ["We", "decorated", "the", "Christmas", "tree", "together", "with", "ornaments", "and", "lights", "We decorated the Christmas tree together with ornaments and lights"] },
    { day: '2024-12-02', words: ["She", "baked", "a", "gingerbread", "house", "and", "decorated", "it", "with", "candy", "and", "frosting", "She baked a gingerbread house and decorated it with candy and frosting"] },
    { day: '2024-12-03', words: ["He", "made", "a", "snow", "angel", "in", "the", "yard", "and", "laughed", "when", "it", "looked", "perfect", "He made a snow angel in the yard and laughed when it looked perfect"] },
    { day: '2024-12-04', words: ["They", "sang", "Christmas", "carols", "door-to-door", "and", "spread", "holiday", "cheer", "They sang Christmas carols door-to-door and spread holiday cheer"] },
    { day: '2024-12-05', words: ["The", "ice", "skaters", "glided", "gracefully", "across", "the", "frozen", "pond", "performing", "elegant", "moves", "The ice skaters glided gracefully across the frozen pond performing elegant moves"] },
    { day: '2024-12-06', words: ["We", "built", "a", "gingerbread", "house", "and", "added", "lots", "of", "colorful", "candies", "We built a gingerbread house and added lots of colorful candies"] },
    { day: '2024-12-07', words: ["She", "wrapped", "presents", "for", "her", "family", "and", "placed", "them", "under", "the", "Christmas", "tree", "She wrapped presents for her family and placed them under the Christmas tree"] },
    { day: '2024-12-08', words: ["He", "hung", "stockings", "by", "the", "fireplace", "and", "decorated", "them", "with", "glitter", "and", "names", "He hung stockings by the fireplace and decorated them with glitter and names"] },
    { day: '2024-12-09', words: ["They", "had", "a", "snowball", "fight", "in", "the", "backyard", "and", "built", "an", "igloo", "They had a snowball fight in the backyard and built an igloo"] },
    { day: '2024-12-10', words: ["The", "Christmas", "lights", "twinkled", "brightly", "on", "the", "house", "and", "lit", "up", "the", "whole", "street", "The Christmas lights twinkled brightly on the house and lit up the whole street"] },
    { day: '2024-12-11', words: ["We", "drank", "hot", "chocolate", "by", "the", "fire", "and", "told", "stories", "We drank hot chocolate by the fire and told stories"] },
    { day: '2024-12-12', words: ["She", "made", "Christmas", "cookies", "and", "decorated", "them", "with", "icing", "and", "sprinkles", "She made Christmas cookies and decorated them with icing and sprinkles"] },
    { day: '2024-12-13', words: ["He", "wrote", "a", "letter", "to", "Santa", "asking", "for", "his", "favorite", "toys", "He wrote a letter to Santa asking for his favorite toys"] },
    { day: '2024-12-14', words: ["They", "went", "sledding", "down", "the", "big", "hill", "and", "had", "so", "much", "fun", "They went sledding down the big hill and had so much fun"] },
    { day: '2024-12-15', words: ["The", "snowflakes", "fell", "gently", "from", "the", "sky", "and", "covered", "everything", "in", "white", "The snowflakes fell gently from the sky and covered everything in white"] },
    { day: '2024-12-16', words: ["We", "made", "a", "snowman", "with", "a", "carrot", "nose", "and", "a", "scarf", "We made a snowman with a carrot nose and a scarf"] },
    { day: '2024-12-17', words: ["She", "knitted", "a", "warm", "scarf", "for", "her", "friend", "as", "a", "Christmas", "gift", "She knitted a warm scarf for her friend as a Christmas gift"] },
    { day: '2024-12-18', words: ["He", "decorated", "the", "Christmas", "tree", "with", "beautiful", "ornaments", "and", "twinkling", "lights", "He decorated the Christmas tree with beautiful ornaments and twinkling lights"] },
    { day: '2024-12-19', words: ["They", "made", "a", "snow", "fort", "and", "played", "inside", "it", "all", "day", "They made a snow fort and played inside it all day"] },
    { day: '2024-12-20', words: ["The", "fireplace", "kept", "the", "house", "warm", "and", "cozy", "during", "the", "cold", "winter", "night", "The fireplace kept the house warm and cozy during the cold winter night"] },
    { day: '2024-12-21', words: ["We", "saw", "a", "reindeer", "at", "the", "zoo", "and", "learned", "about", "its", "habitat", "We saw a reindeer at the zoo and learned about its habitat"] },
    { day: '2024-12-22', words: ["She", "hung", "Christmas", "lights", "on", "the", "tree", "and", "decorated", "it", "with", "colorful", "ornaments", "She hung Christmas lights on the tree and decorated it with colorful ornaments"] },
    { day: '2024-12-23', words: ["He", "made", "a", "Christmas", "ornament", "out", "of", "clay", "and", "painted", "it", "He made a Christmas ornament out of clay and painted it"] },
    { day: '2024-12-24', words: ["They", "watched", "Christmas", "movies", "together", "and", "drank", "hot", "cocoa", "They watched Christmas movies together and drank hot cocoa"] },
    { day: '2024-12-25', words: ["The", "family", "opened", "presents", "on", "Christmas", "morning", "and", "enjoyed", "a", "big", "breakfast", "The family opened presents on Christmas morning and enjoyed a big breakfast"] },
    { day: '2024-12-26', words: ["We", "played", "in", "the", "snow", "all", "day", "and", "built", "a", "huge", "snowman", "We played in the snow all day and built a huge snowman"] },
    { day: '2024-12-27', words: ["She", "made", "a", "beautiful", "snow", "globe", "and", "shook", "it", "to", "see", "the", "snow", "fall", "She made a beautiful snow globe and shook it to see the snow fall"] },
    { day: '2024-12-28', words: ["He", "built", "a", "snow", "fort", "and", "invited", "his", "friends", "to", "play", "inside", "it", "He built a snow fort and invited his friends to play inside it"] },
    { day: '2024-12-29', words: ["They", "drank", "hot", "cocoa", "by", "the", "fire", "and", "shared", "stories", "They drank hot cocoa by the fire and shared stories"] },
    { day: '2024-12-30', words: ["The", "snow", "covered", "the", "trees", "and", "made", "the", "forest", "look", "like", "a", "winter", "wonderland", "The snow covered the trees and made the forest look like a winter wonderland"] },
    { day: '2024-12-31', words: ["We", "celebrated", "New", "Year's", "Eve", "with", "fireworks", "and", "cheered", "as", "the", "clock", "struck", "midnight", "We celebrated New Year's Eve with fireworks and cheered as the clock struck midnight"] }
    ];

/*  Done=====on 24 Aug
const words = [
    { day: '2024-11-01', words: ["We raked leaves", "into a big pile", "and jumped into it", "We raked leaves into a big pile and jumped into it"] },
    { day: '2024-11-02', words: ["She found", "a rare four-leaf clover", "in the grass", "and kept it for good luck", "She found a rare four-leaf clover in the grass and kept it for good luck"] },
    { day: '2024-11-03', words: ["He made", "an impressive sandcastle", "at the beach", "with towers and moats", "He made an impressive sandcastle at the beach with towers and moats"] },
    { day: '2024-11-04', words: ["They had", "a fun barbecue", "in the backyard", "with friends and family", "They had a fun barbecue in the backyard with friends and family"] },
    { day: '2024-11-05', words: ["The wind", "blew the colorful leaves", "off the trees", "and they danced in the air", "The wind blew the colorful leaves off the trees and they danced in the air"] },
    { day: '2024-11-06', words: ["We saw", "a squirrel climb quickly", "up the tree", "and disappear into the branches", "We saw a squirrel climb quickly up the tree and disappear into the branches"] },
    { day: '2024-11-07', words: ["She made", "a huge snowman", "in the front yard", "with a carrot nose and coal eyes", "She made a huge snowman in the front yard with a carrot nose and coal eyes"] },
    { day: '2024-11-08', words: ["He rode", "his skateboard", "at the park", "and performed cool tricks", "He rode his skateboard at the park and performed cool tricks"] },
    { day: '2024-11-09', words: ["They played hide-and-seek", "in the house", "and found great hiding spots", "They played hide-and-seek in the house and found great hiding spots"] },
    { day: '2024-11-10', words: ["The flowers", "bloomed beautifully", "in the spring", "and filled the garden with color", "The flowers bloomed beautifully in the spring and filled the garden with color"] },
    { day: '2024-11-11', words: ["We made", "a fort out of blankets", "and pillows", "and played inside it", "We made a fort out of blankets and pillows and played inside it"] },
    { day: '2024-11-12', words: ["She read", "a captivating story", "to her little brother", "before bedtime", "She read a captivating story to her little brother before bedtime"] },
    { day: '2024-11-13', words: ["He drew", "a detailed map", "of his neighborhood", "including all the houses and streets", "He drew a detailed map of his neighborhood including all the houses and streets"] },
    { day: '2024-11-14', words: ["They played", "an exciting board game", "on a rainy day", "and laughed a lot", "They played an exciting board game on a rainy day and laughed a lot"] },
    { day: '2024-11-15', words: ["The butterfly", "landed gently", "on a flower", "and sipped nectar", "The butterfly landed gently on a flower and sipped nectar"] },
    { day: '2024-11-16', words: ["We saw", "an exciting movie", "at the theater", "with lots of action and adventure", "We saw an exciting movie at the theater with lots of action and adventure"] },
    { day: '2024-11-17', words: ["She made", "a colorful card", "for her friend's birthday", "and decorated it with stickers", "She made a colorful card for her friend's birthday and decorated it with stickers"] },
    { day: '2024-11-18', words: ["He helped", "his mom cook", "a delicious dinner", "and set the table", "He helped his mom cook a delicious dinner and set the table"] },
    { day: '2024-11-19', words: ["They went", "for a peaceful walk", "in the forest", "and saw many different animals", "They went for a peaceful walk in the forest and saw many different animals"] },
    { day: '2024-11-20', words: ["The snow", "covered the ground", "overnight", "and made everything look like a winter wonderland", "The snow covered the ground overnight and made everything look like a winter wonderland"] },
    { day: '2024-11-21', words: ["We had", "hot chocolate", "on a cold day", "and warmed up by the fire", "We had hot chocolate on a cold day and warmed up by the fire"] },
    { day: '2024-11-22', words: ["She wrote", "an interesting story", "about a magical forest", "filled with mystical creatures", "She wrote an interesting story about a magical forest filled with mystical creatures"] },
    { day: '2024-11-23', words: ["He built", "a model airplane", "and painted it", "with bright colors", "He built a model airplane and painted it with bright colors"] },
    { day: '2024-11-24', words: ["They went", "on an exciting treasure hunt", "and found", "hidden gems", "They went on an exciting treasure hunt and found hidden gems"] },
    { day: '2024-11-25', words: ["The sunset", "was a beautiful shade", "of orange and pink", "and we watched it together", "The sunset was a beautiful shade of orange and pink and we watched it together"] },
    { day: '2024-11-26', words: ["We had", "a fun snowball fight", "in the yard", "and built a snow fort", "We had a fun snowball fight in the yard and built a snow fort"] },
    { day: '2024-11-27', words: ["She made", "a beautiful necklace", "out of shells", "and gave it to her mother", "She made a beautiful necklace out of shells and gave it to her mother"] },
    { day: '2024-11-28', words: ["He played catch", "with his dog", "in the backyard", "and taught it new tricks", "He played catch with his dog in the backyard and taught it new tricks"] },
    { day: '2024-11-29', words: ["They had", "a sleepover", "at their friend's house", "and stayed up late telling stories", "They had a sleepover at their friend's house and stayed up late telling stories"] },
    { day: '2024-11-30', words: ["The fireworks", "lit up the night sky", "with bright colors", "and loud bangs", "The fireworks lit up the night sky with bright colors and loud bangs"] }
];

const words = [
    { day: '2024-11-01', words: ["We", "raked", "leaves", "into", "a", "big", "pile", "and", "jumped", "into", "it", "We raked leaves into a big pile and jumped into it"] },
    { day: '2024-11-02', words: ["She", "found", "a", "rare", "four-leaf", "clover", "in", "the", "grass", "and", "kept", "it", "for", "good", "luck", "She found a rare four-leaf clover in the grass and kept it for good luck"] },
    { day: '2024-11-03', words: ["He", "made", "an", "impressive", "sandcastle", "at", "the", "beach", "with", "towers", "and", "moats", "He made an impressive sandcastle at the beach with towers and moats"] },
    { day: '2024-11-04', words: ["They", "had", "a", "fun", "barbecue", "in", "the", "backyard", "with", "friends", "and", "family", "They had a fun barbecue in the backyard with friends and family"] },
    { day: '2024-11-05', words: ["The", "wind", "blew", "the", "colorful", "leaves", "off", "the", "trees", "and", "they", "danced", "in", "the", "air", "The wind blew the colorful leaves off the trees and they danced in the air"] },
    { day: '2024-11-06', words: ["We", "saw", "a", "squirrel", "climb", "quickly", "up", "the", "tree", "and", "disappear", "into", "the", "branches", "We saw a squirrel climb quickly up the tree and disappear into the branches"] },
    { day: '2024-11-07', words: ["She", "made", "a", "huge", "snowman", "in", "the", "front", "yard", "with", "a", "carrot", "nose", "and", "coal", "eyes", "She made a huge snowman in the front yard with a carrot nose and coal eyes"] },
    { day: '2024-11-08', words: ["He", "rode", "his", "skateboard", "at", "the", "park", "and", "performed", "cool", "tricks", "He rode his skateboard at the park and performed cool tricks"] },
    { day: '2024-11-09', words: ["They", "played", "hide-and-seek", "in", "the", "house", "and", "found", "great", "hiding", "spots", "They played hide-and-seek in the house and found great hiding spots"] },
    { day: '2024-11-10', words: ["The", "flowers", "bloomed", "beautifully", "in", "the", "spring", "and", "filled", "the", "garden", "with", "color", "The flowers bloomed beautifully in the spring and filled the garden with color"] },
    { day: '2024-11-11', words: ["We", "made", "a", "fort", "out", "of", "blankets", "and", "pillows", "and", "played", "inside", "it", "We made a fort out of blankets and pillows and played inside it"] },
    { day: '2024-11-12', words: ["She", "read", "a", "captivating", "story", "to", "her", "little", "brother", "before", "bedtime", "She read a captivating story to her little brother before bedtime"] },
    { day: '2024-11-13', words: ["He", "drew", "a", "detailed", "map", "of", "his", "neighborhood", "including", "all", "the", "houses", "and", "streets", "He drew a detailed map of his neighborhood including all the houses and streets"] },
    { day: '2024-11-14', words: ["They", "played", "an", "exciting", "board", "game", "on", "a", "rainy", "day", "and", "laughed", "a", "lot", "They played an exciting board game on a rainy day and laughed a lot"] },
    { day: '2024-11-15', words: ["The", "butterfly", "landed", "gently", "on", "a", "flower", "and", "sipped", "nectar", "The butterfly landed gently on a flower and sipped nectar"] },
    { day: '2024-11-16', words: ["We", "saw", "an", "exciting", "movie", "at", "the", "theater", "with", "lots", "of", "action", "and", "adventure", "We saw an exciting movie at the theater with lots of action and adventure"] },
    { day: '2024-11-17', words: ["She", "made", "a", "colorful", "card", "for", "her", "friend's", "birthday", "and", "decorated", "it", "with", "stickers", "She made a colorful card for her friend's birthday and decorated it with stickers"] },
    { day: '2024-11-18', words: ["He", "helped", "his", "mom", "cook", "a", "delicious", "dinner", "and", "set", "the", "table", "He helped his mom cook a delicious dinner and set the table"] },
    { day: '2024-11-19', words: ["They", "went", "for", "a", "peaceful", "walk", "in", "the", "forest", "and", "saw", "many", "different", "animals", "They went for a peaceful walk in the forest and saw many different animals"] },
    { day: '2024-11-20', words: ["The", "snow", "covered", "the", "ground", "overnight", "and", "made", "everything", "look", "like", "a", "winter", "wonderland", "The snow covered the ground overnight and made everything look like a winter wonderland"] },
    { day: '2024-11-21', words: ["We", "had", "hot", "chocolate", "on", "a", "cold", "day", "and", "warmed", "up", "by", "the", "fire", "We had hot chocolate on a cold day and warmed up by the fire"] },
    { day: '2024-11-22', words: ["She", "wrote", "an", "interesting", "story", "about", "a", "magical", "forest", "filled", "with", "mystical", "creatures", "She wrote an interesting story about a magical forest filled with mystical creatures"] },
    { day: '2024-11-23', words: ["He", "built", "a", "model", "airplane", "and", "painted", "it", "with", "bright", "colors", "He built a model airplane and painted it with bright colors"] },
    { day: '2024-11-24', words: ["They", "went", "on", "an", "exciting", "treasure", "hunt", "and", "found", "hidden", "gems", "They went on an exciting treasure hunt and found hidden gems"] },
    { day: '2024-11-25', words: ["The", "sunset", "was", "a", "beautiful", "shade", "of", "orange", "and", "pink", "and", "we", "watched", "it", "together", "The sunset was a beautiful shade of orange and pink and we watched it together"] },
    { day: '2024-11-26', words: ["We", "had", "a", "fun", "snowball", "fight", "in", "the", "yard", "and", "built", "a", "snow", "fort", "We had a fun snowball fight in the yard and built a snow fort"] },
    { day: '2024-11-27', words: ["She", "made", "a", "beautiful", "necklace", "out", "of", "shells", "and", "gave", "it", "to", "her", "mother", "She made a beautiful necklace out of shells and gave it to her mother"] },
    { day: '2024-11-28', words: ["He", "played", "catch", "with", "his", "dog", "in", "the", "backyard", "and", "taught", "it", "new", "tricks", "He played catch with his dog in the backyard and taught it new tricks"] },
    { day: '2024-11-29', words: ["They", "had", "a", "sleepover", "at", "their", "friend's", "house", "and", "stayed", "up", "late", "telling", "stories", "They had a sleepover at their friend's house and stayed up late telling stories"] },
    { day: '2024-11-30', words: ["The", "fireworks", "lit", "up", "the", "night", "sky", "with", "bright", "colors", "and", "loud", "bangs", "The fireworks lit up the night sky with bright colors and loud bangs"] }
]; */
  
